<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'About Me',
    'About Me' => 'About Me',
    'Address' => 'Address',
    'Close (Esc)' => 'Close (Esc)',
    'Choose category...' => 'Choose category...',
    'Email' => 'E-mail',
    'Home' => 'Home',
    'Message' => 'Message',
    'Name' => 'Your Name',
    'Phone' => 'Phone',
    'Subject' => 'Subject',
    'Verification Code' => 'Verification Code',
    'Visit Home Page' => 'Visit Home Page',
    'Socials' => 'Socials',
    'We are open' => 'We are open',
    'Opening hours' => 'Opening hours',
    'Contact Me' => 'Contact Me',
    'Contact info' => 'Contact info',
    'Contacts' => 'Contacts',
    'Courses' => 'Courses',
    'Create an Account' => 'Create an Account',
    'Enter keyword and hit Enter...' => 'Enter keyword and hit Enter...',
    'Go!' => 'Go!',
    'If you have questions' => 'If you have questions',
    'Next (arrow right)' => 'Next (arrow right)',
    'No results found...' => 'No results found...',
    'Page not Found' => 'Page not Found',
    'Phones' => 'Phones',
    'Previous (arrow left)' => 'Previous (arrow left)',
    'Profile' => 'Profile',
    'Recent Comments' => 'Recent Comments',
    'Request a call' => 'Request a call',
    'Search' => 'Search',
    'Search results' => 'Search results',
    'Share' => 'Share',
    'Sign In' => 'Sign In',
    'Sign Out' => 'Sign Out',
    'Submit' => 'Send',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Thank you for contacting us. We will respond to you as soon as possible.',
    'This Site is Coming Soon' => 'This Site is Coming Soon',
    'Toggle fullscreen' => 'Toggle fullscreen',
    'You can fill out the form below and we will contact you shortly.' => 'You can fill out the form below and we will contact you shortly.',
    'Zoom in/out' => 'Zoom in/out',
    // Page Title
    'Your search:' => 'Your search:',
    'Testimonials' => 'Testimonials',
    'We\'re getting ready to launch in' => 'We\'re getting ready to launch in',
    'days' => 'days',
    'hours' => 'hours',
    'minutes' => 'minutes',
    'seconds' => 'seconds',
    'Our website is under construction, we are working very hard to give you the best experience on our new web site.' => 'Our website is under construction, we are working very hard to give you the best experience on our new web site.',
    // Coockies and other Errors
    'Coockies Warnings' => 'Work on this site, вы даете свое согласие на использование файлов cookie сервисов Google. Это необходимо для нормального функционирования сайта, показа целевой рекламы и анализа трафика. Статистика использования сайта отправляется в Google',
];