<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Обо Мне',
    'About Us' => 'Обо Мне',
    'Address' => 'Адрес',
    'Close (Esc)' => 'Закрыть (Esc)',
    'Contacts' => 'Контакты',
    'Courses' => 'Курсы',
    'Create an Account' => 'Зарегистрироваться',
    'Email' => 'E-mail',
    'Home' => 'Главная',
    'Message' => 'Сообщение',
    'Name' => 'Имя Фамилия',
    'Page not Found' => 'Страница не найдена',
    'Phone' => 'Телефон',
    'Subject' => 'Тема',
    'Verification Code' => 'Проверочный код',
    'Visit Home Page' => 'Перейти на главную',
    'Socials' => 'Социалки',
    'We are open' => 'Мы работаем',
    'Opening hours' => 'Время работы',
    'Choose category...' => 'Выберите категорию...',
    'Contact Me' => 'Связаться со мной',
    'Contact info' => 'Контактная информация',
    'Enter keyword and hit Enter...' => 'Введите ключевое слово и нажмите Enter...',
    'Go!' => 'Go!',
    'If you have questions' => 'Если у вас есть вопросы',
    'Next (arrow right)' => '',
    'No results found...' => 'Результаты не найдены...',
    'Phones' => 'Телефоны',
    'Previous (arrow left)' => '',
    'Profile' => 'Профиль',
    'Recent Comments' => '',
    'Request a call' => 'Заказать звонок',
    'Search' => 'Поиск',
    'Search results' => 'Результаты поиска',
    'Share' => '',
    'Sign In' => 'Войти',
    'Sign Out' => 'Выйти',
    'Submit' => 'Отправить',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Благодарим Вас за обращение к нам. Мы ответим Вам как можно скорее.',
    'This Site is Coming Soon' => 'Этот сайт скоро появится',
    'Toggle fullscreen' => 'Включить полноэкранный режим',
    'You can fill out the form below and we will contact you shortly.' => 'Вы можете заполнить форму ниже, и мы свяжемся с вами в ближайшее время.',
    'Zoom in/out' => 'Увеличить / уменьшить',
    // Page Title
    'Your search:' => 'Вы искали:',
    'Testimonials' => 'Отзывы',
    'We\'re getting ready to launch in' => 'Мы готовимся к запуску через',
    'days' => 'дней',
    'hours' => 'часов',
    'minutes' => 'минут',
    'seconds' => 'секунд',
    'Our website is under construction, we are working very hard to give you the best experience on our new web site.' => 'Наш сайт находится в стадии разработки, мы прилагаем все усилия, чтобы дать Вам больше информации и комфорта на нашем новом веб-сайте.',
    // Coockies and other Errors
    'Coockies Warnings' => 'Работая с этим сайтом, Вы даете свое согласие на использование файлов cookie сервисами Google и самим сайтом. Это необходимо для нормального функционирования сайта, для работы личного кабинета и магазина, анализа трафика. Статистика использования сайта отправляется в Google',
];